---
- name: "chrony | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "chrony | Include packages tasks"
  ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['chrony'] is defined"
    - "hostvars[inventory_hostname]['chrony'] != ''"
    - "hostvars[inventory_hostname]['chrony'] |
       community.general.json_query(vars['chrony_install_package']) is defined"
    - "hostvars[inventory_hostname]['chrony'] |
       community.general.json_query(vars['chrony_install_package']) == 'true'"
  vars:
    chrony_install_package: "[] | map(&install_package || 'false', @) | [0]"
- name: "chrony | Include deployment tasks"
  ansible.builtin.import_tasks:
    file: "deploy_chrony.yml"
